def count_equal_xo_groups(s: str) -> int:
    count_x = 0
    count_o = 0
    groups = 0

    for char in s:
        if char == 'X':
            count_x += 1
        elif char == 'O':
            count_o += 1

        # Check if counts of X and O are equal
        if count_x == count_o:
            groups += 1
            # Reset counters for the next group
            count_x = 0
            count_o = 0

    return groups

# Example usage
input_string = "XXXOOOXXOXOOOXOXOOXOXXOOOOOXXOXOOOOOOOOOXOOXXXOXOOOOXXOXOXXOXXXXXXXXXXXXOXOOOXXOXOOXOXXXXOOOXOOXXXXXXOXOOXOXXXXOOXOXXXOXOOXOOXOXXOOOOXXXXXXOOOXXOXXXXXOOOOOXXXOOXXOXOOOOXXOOXOXXXOOXOOXOXXOXXOXOOOOOOXOOOXOXOXXOOXXOOXOXOXOXXOOOXXXXOOXXOXXXXXOOXOOOOOOOOOOOOOXOXXXOOOXOOXXXXOXXOOOOOOOXXOOOOXXOXXXXOOXXXXOXOOXXXXOOXOOOXXXXXXOXXOOOXXXOOXOXXOXXOOOOXXOXOXXOXOXXXOXOXXXXOOXOXXOXXXXOXOOOXOOXXOOXXXOXOXXOXXXXXOOXXXOOXOXOOOOOOOXXOOOXOXOXOOXOXXXOXOOXOOXXOXOOXOOXXOXOOOOXXOXXXOOOXOXXXXOOOXXXXOXXXOOXOXOOOXOOOOOXOXXOOXXXXOOOXOXOXOOXOOXOXXXXXXXOOXOXOXOXXOOXOOXOOXOXOXOXXOXOOXXXXOOXOOXOXOOXOOXXXOOXXXOXXOOOOXXOOXOOOOXOXOXOXXOXXXXOXXXXXXOXXXXXOXXOOXXXXOOXOXOOOXOOOXOOOXXOXOOXOXXOOOXXXOOOOXXOOXXXOOXXXOXOXXOXOOOOOOOXXOXXOOXOXOOXXXXXXOXXXXXXXOXOXXXXXXOOXXOOOXXOXOXOXOXOXXXOOXOXXXOXXXXXOOOXXXXOXXOXOOOOOXOXOXOXOOXOXOXXOXOOOOXOOXXOOXXOXXXXOOXXOXXOOOOOXOOOXOOXOOOXOXXOOXOXXXXXXOXXXXXOOOOXXXXXOOXXXOXXOOOXOOOXOOOXOXXXOOXXXOOOOOOXOOXXXOOOXXXXOOOOXXOOXOOXXOXOXOXXOOXXXOXOOOOOXXXOOOXOOOOOOXXOOXOXXXOXOXXXOXXOOXXOOOXXOOXXOOOXXOXO"
result = count_equal_xo_groups(input_string)
print(f"The largest number of groups with equal 'X's and 'O's is: {result}")
