def max_fair_groups(s: str) -> int:
    # Initialize variables to track fair groups and counts
    count_x = 0
    count_o = 0
    fair_groups = 0

    # Iterate through the string
    for char in s:
        if char == "X":
            count_x += 1
        elif char == "O":
            count_o += 1

        # If counts match, a fair group is formed
        if count_x == count_o:
            fair_groups += 1
            # Reset counts for the next group
            count_x = 0
            count_o = 0

    return fair_groups


print(max_fair_groups("XXXOOOXXOXOOOXOXOOXOXXOOOOOXXOXOOOOOOOOOXOOXXXOXOOOOXXOXOXXOXXXXXXXXXXXXOXOOOXXOXOOXOXXXXOOOXOOXXXXXXOXOOXOXXXXOOXOXXXOXOOXOOXOXXOOOOXXXXXXOOOXXOXXXXXOOOOOXXXOOXXOXOOOOXXOOXOXXXOOXOOXOXXOXXOXOOOOOOXOOOXOXOXXOOXXOOXOXOXOXXOOOXXXXOOXXOXXXXXOOXOOOOOOOOOOOOOXOXXXOOOXOOXXXXOXXOOOOOOOXXOOOOXXOXXXXOOXXXXOXOOXXXXOOXOOOXXXXXXOXXOOOXXXOOXOXXOXXOOOOXXOXOXXOXOXXXOXOXXXXOOXOXXOXXXXOXOOOXOOXXOOXXXOXOXXOXXXXXOOXXXOOXOXOOOOOOOXXOOOXOXOXOOXOXXXOXOOXOOXXOXOOXOOXXOXOOOOXXOXXXOOOXOXXXXOOOXXXXOXXXOOXOXOOOXOOOOOXOXXOOXXXXOOOXOXOXOOXOOXOXXXXXXXOOXOXOXOXXOOXOOXOOXOXOXOXXOXOOXXXXOOXOOXOXOOXOOXXXOOXXXOXXOOOOXXOOXOOOOXOXOXOXXOXXXXOXXXXXXOXXXXXOXXOOXXXXOOXOXOOOXOOOXOOOXXOXOOXOXXOOOXXXOOOOXXOOXXXOOXXXOXOXXOXOOOOOOOXXOXXOOXOXOOXXXXXXOXXXXXXXOXOXXXXXXOOXXOOOXXOXOXOXOXOXXXOOXOXXXOXXXXXOOOXXXXOXXOXOOOOOXOXOXOXOOXOXOXXOXOOOOXOOXXOOXXOXXXXOOXXOXXOOOOOXOOOXOOXOOOXOXXOOXOXXXXXXOXXXXXOOOOXXXXXOOXXXOXXOOOXOOOXOOOXOXXXOOXXXOOOOOOXOOXXXOOOXXXXOOOOXXOOXOOXXOXOXOXXOOXXXOXOOOOOXXXOOOXOOOOOOXXOOXOXXXOXOXXXOXXOOXXOOOXXOOXXOOOXXOXO"))